### PR TITLE
FDB Parsing functionality and some changes in CONTRIBUTING.rst and some configs

### PR DESCRIPTION
**Pull request by inaciomdrs**
### Changelog

* Implements FDB parsing from FASTA
* Suggests some changes in CONTRIBUTING.rst and some config files...

### What I Did...

```
Implements FDB parsing functionality (which parses fasta input file into fdb format) and, based on experience that I've got in pulling repository and configuring it, gives some suggestions for CONTRIBUTING.rst file and some config files, such that "installing proccess" runs "without much problems" (I confess that I've got some problems in installing and configuring this project, and needed to make some changes in somethings for make stuff "runs easier", so here we are).
```

### CODE REVIEW

**Comment by vmesel** [comment]
For the useless code that are commented on the code, please remove it! For the setup functionalities, let's not use them right now so we can, first, the lib working, than the setup for other users to consume it.

**Comment by vmesel** [comment]
Please, remove the PYC, EggInfo and other compiled and other things, it can damage the source code and make it look less attractive

**Comment by inaciomdrs** [comment]
Roger that

**Comment by inaciomdrs** [comment]
@vmesel I've done right now changes that you've advised. I've removed egg stuff, __pycache__ ones, and deleted commented codes. By now, must I make a new pull request?

**Pull request merged**
